# Generated by Django 2.2.3 on 2020-02-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('message_text', models.CharField(max_length=5000)),
                ('isShow', models.BooleanField(default=True)),
            ],
        ),
    ]
