# Generated by Django 2.2.3 on 2020-02-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20200219_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='isShow',
            field=models.BooleanField(default=False),
        ),
    ]
