# Generated by Django 2.2.3 on 2020-02-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20200219_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='classNum',
            field=models.CharField(default='1班', max_length=2),
        ),
        migrations.AddField(
            model_name='message',
            name='grade',
            field=models.CharField(default='一年级', max_length=3),
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='', max_length=8),
        ),
    ]
