# Generated by Django 2.2.3 on 2020-02-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20200223_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '留言', 'verbose_name_plural': '留言'},
        ),
        migrations.AlterField(
            model_name='message',
            name='classNum',
            field=models.CharField(default='1班', max_length=2, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='message',
            name='grade',
            field=models.CharField(default='一年级', max_length=3, verbose_name='年级'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='isShow',
            field=models.BooleanField(default=False, verbose_name='是否显示'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.TextField(max_length=5000, verbose_name='留言内容'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(default='', max_length=8, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=100, verbose_name='留言标题'),
        ),
    ]
